/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.rodrigoloq.reto_conversor;

import javax.swing.JOptionPane;

/**
 *
 * @author RL123
 */
public class conversor_menu4 extends javax.swing.JFrame {

    double cantidadconvertida = 0;
    double temperaturaconvertida = 0;

    /**
     * Creates new form conversor_menu2
     */
    public conversor_menu4() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    public conversor_menu4(String seleccion, double cantidad, String cboseleccion) {
        initComponents();
        this.setLocationRelativeTo(null);

        if (cboseleccion == "Conversor de monedas") {
            conversorMoneda(seleccion, cantidad);
        } else if (cboseleccion == "Conversor de temperaturas") {
            conversorTemperatura(seleccion, cantidad);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCantidadConvertida = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        lblCantidadConvertida.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton1.setText("Ok");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(lblCantidadConvertida)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(43, 43, 43))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(lblCantidadConvertida)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(42, 42, 42))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        conversor_menu5 menu5 = new conversor_menu5();
        menu5.setVisible(rootPaneCheckingEnabled);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(conversor_menu4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(conversor_menu4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(conversor_menu4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(conversor_menu4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new conversor_menu4().setVisible(true);
            }
        });
    }

    public void conversorMoneda(String seleccion, double cantidad) {
        if (seleccion == "De Sol Peruano a Dolar") {
            cantidadconvertida = cantidad * 0.27;
        }
        if (seleccion == "De Sol Peruano a Euro") {
            cantidadconvertida = cantidad * 0.25;
        }
        if (seleccion == "De Sol Peruano a Libra Esterlina") {
            cantidadconvertida = cantidad * 0.22;
        }
        if (seleccion == "De Sol Peruano a Yen Japonés") {
            cantidadconvertida = cantidad * 35.53;
        }
        if (seleccion == "De Sol Peruano a Won sul-coreano") {
            cantidadconvertida = cantidad * 351.59;
        }
        if (seleccion == "De Dolar a Sol Peruano") {
            cantidadconvertida = cantidad * 3.76;
        }
        if (seleccion == "De Euro a Sol Peruano") {
            cantidadconvertida = cantidad * 4.06;
        }
        if (seleccion == "De Libra Esterlina a Sol Peruano") {
            cantidadconvertida = cantidad * 4.62;
        }
        if (seleccion == "De Yen Japonés a Sol Peruano") {
            cantidadconvertida = cantidad * 0.028;
        }
        if (seleccion == "De Won sul-coreano a Sol Peruano") {
            cantidadconvertida = cantidad * 0.0029;
        }

        lblCantidadConvertida.setText("Tienes: " + Math.round(cantidadconvertida));
    }

    public void conversorTemperatura(String seleccion, double temperatura) {
        if (seleccion == "De Grado Celsius a Grado Fahrenheit") {
            cantidadconvertida = ((temperatura * 9) / 5) + 32;
        }
        if (seleccion == "De Grado Celsius a Kelvin") {
            cantidadconvertida = temperatura + 273.15;
        }
        if (seleccion == "De Grado Fahrenheit a Kelvin") {
            cantidadconvertida = (((temperatura - 32) * 5) / 9) + 273.15;
        }
        if (seleccion == "De Grado Fahrenheit a Grado Celsius") {
            cantidadconvertida = (((temperatura - 32) * 5) / 9);
        }
        if (seleccion == "De Kelvin a Grado Celsius") {
            cantidadconvertida = temperatura - 273.15;
        }
        if (seleccion == "De Kelvin a Grado Fahrenheit") {
            cantidadconvertida = (((temperatura - 273.15) * 9) / 5) + 32;
        }

        lblCantidadConvertida.setText("Tienes: " + Math.round(cantidadconvertida));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel lblCantidadConvertida;
    // End of variables declaration//GEN-END:variables
}
